import type { AnalysisGraph } from '@codeviz/shared';

/** Demo graph so the canvas is explorable before running a real analysis. */
export const demoGraph: AnalysisGraph = {
  repo: {
    name: 'acme-shop (demo)',
    source: { type: 'github', url: 'https://github.com/acme/shop' },
    analyzedAt: new Date().toISOString(),
  },
  components: [
    {
      id: 'web',
      name: 'web',
      path: 'apps/web',
      type: 'frontend',
      languages: ['typescript'],
      files: ['apps/web/src/App.tsx', 'apps/web/src/api.ts', 'apps/web/src/cart.tsx'],
      routes: [],
      outboundCalls: [
        { kind: 'http', target: '/api/products', file: 'apps/web/src/api.ts', line: 12 },
        { kind: 'http', target: '/api/cart', file: 'apps/web/src/api.ts', line: 31 },
      ],
      metrics: { loc: 4210, fileCount: 38, fanIn: 0, fanOut: 2 },
      summary: 'React storefront. Talks to the API gateway for products, cart and checkout.',
      bottlenecks: [],
    },
    {
      id: 'api',
      name: 'api',
      path: 'services/api',
      type: 'service',
      languages: ['typescript'],
      files: ['services/api/src/server.ts', 'services/api/src/routes/products.ts'],
      routes: [
        { method: 'GET', path: '/api/products', file: 'services/api/src/routes/products.ts', line: 14 },
        { method: 'POST', path: '/api/cart', file: 'services/api/src/routes/cart.ts', line: 9 },
        { method: 'POST', path: '/api/checkout', file: 'services/api/src/routes/checkout.ts', line: 21 },
      ],
      outboundCalls: [
        { kind: 'db', target: 'PrismaClient', file: 'services/api/src/db.ts', line: 4 },
        { kind: 'lambda', target: 'send-receipt', file: 'services/api/src/routes/checkout.ts', line: 44 },
        { kind: 'http', target: 'https://api.stripe.com/v1/charges', file: 'services/api/src/pay.ts', line: 17 },
      ],
      metrics: { loc: 6120, fileCount: 24, fanIn: 1, fanOut: 3 },
      summary:
        'Express API gateway. Serves product/cart/checkout routes, persists via Prisma, charges Stripe synchronously during checkout.',
      bottlenecks: [
        {
          severity: 'medium',
          reason: 'Synchronous Stripe call inside the checkout request path',
          evidence: 'services/api/src/pay.ts:17 — external latency is user-facing',
          source: 'llm',
        },
      ],
    },
    {
      id: 'catalog-lib',
      name: 'catalog',
      path: 'packages/catalog',
      type: 'library',
      languages: ['typescript'],
      files: ['packages/catalog/src/index.ts'],
      routes: [],
      outboundCalls: [],
      metrics: { loc: 1830, fileCount: 9, fanIn: 2, fanOut: 0 },
      summary: 'Shared product-catalog domain models and validation.',
      bottlenecks: [],
    },
    {
      id: 'lambda-send-receipt',
      name: 'send-receipt',
      path: 'lambdas/receipt',
      type: 'lambda',
      languages: ['python'],
      files: ['lambdas/receipt/handler.py'],
      routes: [],
      outboundCalls: [
        { kind: 'queue', target: 'boto3:sqs', file: 'lambdas/receipt/handler.py', line: 8 },
        { kind: 'storage', target: 'boto3:s3', file: 'lambdas/receipt/handler.py', line: 9 },
      ],
      metrics: { loc: 320, fileCount: 2, fanIn: 1, fanOut: 0 },
      summary: 'Renders and emails order receipts; archives copies to S3.',
      bottlenecks: [
        {
          severity: 'medium',
          reason: 'I/O calls inside loops (2 sites) — possible N+1 pattern',
          evidence: 'lambdas/receipt/handler.py:23 requests.get(item_url)',
          source: 'static',
        },
      ],
    },
    {
      id: 'worker',
      name: 'indexer',
      path: 'services/indexer',
      type: 'service',
      languages: ['go'],
      files: ['services/indexer/main.go'],
      routes: [{ method: '*', path: '/healthz', file: 'services/indexer/main.go', line: 30 }],
      outboundCalls: [
        { kind: 'db', target: 'sql.Open', file: 'services/indexer/main.go', line: 41 },
        { kind: 'queue', target: 'aws:sqs', file: 'services/indexer/main.go', line: 12 },
      ],
      metrics: { loc: 2740, fileCount: 11, fanIn: 0, fanOut: 2 },
      summary: 'Consumes catalog-update events from SQS and refreshes the search index.',
      bottlenecks: [],
    },
    {
      id: 'db-sql',
      name: 'SQL database',
      path: '(shared data store)',
      type: 'database',
      kindDetail: 'SQL database',
      languages: [],
      files: [],
      routes: [],
      outboundCalls: [],
      metrics: { loc: 0, fileCount: 0, fanIn: 2, fanOut: 0 },
      bottlenecks: [
        {
          severity: 'medium',
          reason: 'Shared SQL database — 2 components depend on it directly',
          evidence: 'api, indexer',
          source: 'static',
        },
      ],
    },
    {
      id: 'ext-stripe',
      name: 'api.stripe.com',
      path: '(external dependency)',
      type: 'external',
      kindDetail: 'api.stripe.com',
      languages: [],
      files: [],
      routes: [],
      outboundCalls: [],
      metrics: { loc: 0, fileCount: 0, fanIn: 1, fanOut: 0 },
      bottlenecks: [],
    },
  ],
  edges: [
    { id: 'web→api:http', source: 'web', target: 'api', kind: 'http', count: 2, details: [{ file: 'apps/web/src/api.ts', line: 12 }] },
    { id: 'api→db-sql:db', source: 'api', target: 'db-sql', kind: 'db', count: 4, details: [{ file: 'services/api/src/db.ts', line: 4 }] },
    { id: 'worker→db-sql:db', source: 'worker', target: 'db-sql', kind: 'db', count: 2, details: [{ file: 'services/indexer/main.go', line: 41 }] },
    { id: 'api→ext-stripe:http', source: 'api', target: 'ext-stripe', kind: 'http', count: 1, details: [{ file: 'services/api/src/pay.ts', line: 17 }] },
    { id: 'api→catalog-lib:import', source: 'api', target: 'catalog-lib', kind: 'import', count: 6, details: [{ file: 'services/api/src/routes/products.ts', line: 2 }] },
    { id: 'web→catalog-lib:import', source: 'web', target: 'catalog-lib', kind: 'import', count: 3, details: [{ file: 'apps/web/src/cart.tsx', line: 1 }] },
    { id: 'api→lambda-send-receipt:invoke', source: 'api', target: 'lambda-send-receipt', kind: 'invoke', count: 1, details: [{ file: 'services/api/src/routes/checkout.ts', line: 44, note: 'send-receipt' }] },
    { id: 'worker→catalog-lib:import', source: 'worker', target: 'catalog-lib', kind: 'import', count: 2, details: [{ file: 'services/indexer/main.go', line: 7 }] },
  ],
};
